from pydantic import BaseModel, EmailStr
from typing import Optional
import datetime

# This is the base model with fields common to all other models
class CitizenBase(BaseModel):
    full_name: str
    nic_no: str
    phone_no: str
    email: EmailStr

# Model for creating a new citizen (what the API expects in a POST request)
class CitizenCreate(CitizenBase):
    password: str
    confirm_password: str

# Model for reading a citizen's data (what the API will return)
# This includes fields generated by the database, like id and created_at
class Citizen(CitizenBase):
    citizen_id: str
    created_at: datetime.datetime

    # This tells Pydantic to read the data even if it's not a dict,
    # but an ORM model (like the one from Prisma)
    class Config:
        orm_mode = True